services:
  # Frontend services
  frontend1:
    image: franciscoxd1123/monopb-frontend:latest
    networks:
      - frontend-network

  frontend2:
    image: franciscoxd1123/monopb-frontend:latest
    networks:
      - frontend-network

  frontend3:
    image: franciscoxd1123/monopb-frontend:latest
    networks:
      - frontend-network

  # Backend services
  backend1:
    image: franciscoxd1123/monopb-backend:latest
    environment:
      - DB_HOST=postgres
    networks:
      - backend-network

  backend2:
    image: franciscoxd1123/monopb-backend:latest
    environment:
      - DB_HOST=postgres
    networks:
      - backend-network

  backend3:
    image: franciscoxd1123/monopb-backend:latest
    environment:
      - DB_HOST=postgres
    networks:
      - backend-network

  # PostgreSQL service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbWebMonolitica  # Nombre de la base de datos
      POSTGRES_USER: postgres      # Usuario de la base de datos
      POSTGRES_PASSWORD: MyPostgre74SQL38 # Contraseña para el usuario
    ports:
      - "5433:5432"  # Expone el puerto 5432 para acceso externo
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia de datos
    networks:
      - backend-network

  # Nginx for frontend load balancing
  nginx-frontend:
    image: nginx:latest
    ports:
      - "8070:80"  # Expose port 8070 for external access
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf  # Mount frontend Nginx config
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  # Nginx for backend load balancing
  nginx-backend:
    image: nginx:latest
    ports:
      - "8095:8095"  # Expose port 8095 for external access
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf  # Mount backend Nginx config
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network:

volumes:
  postgres_data: