version: "3.8"

services:
  # Frontend services
  frontend1:
    image: monopb-frontend
    networks:
      - frontend-network

  frontend2:
    image: monopb-frontend
    networks:
      - frontend-network

  frontend3:
    image: monopb-frontend
    networks:
      - frontend-network

  # Backend services
  backend1:
    image: monopb-backend
    environment:
      - DB_HOST=192.168.100.10
    networks:
      - backend-network

  backend2:
    image: monopb-backend
    environment:
      - DB_HOST=192.168.100.10
    networks:
      - backend-network

  backend3:
    image: monopb-backend
    environment:
      - DB_HOST=192.168.100.10
    networks:
      - backend-network

  # Nginx for frontend load balancing
  nginx-frontend:
    image: nginx:latest
    ports:
      - "8070:80"  # Expose port 8070 for external access
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf  # Mount frontend Nginx config
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  # Nginx for backend load balancing
  nginx-backend:
    image: nginx:latest
    ports:
      - "8095:8095"  # Expose port 8095 for external access
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf  # Mount backend Nginx config
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network: